// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('Register User', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('Register User', async function() {
    await driver.get("http://localhost:3000/")
    await driver.manage().window().setRect({ width: 1720, height: 934 })
    await driver.findElement(By.linkText("Login/SignUp")).click()
    await driver.findElement(By.css(".mb-3:nth-child(1) > .form-control")).sendKeys("admin@venus.com")
    await driver.findElement(By.css(".mb-3:nth-child(2) > .form-control")).sendKeys("pass")
    await driver.findElement(By.linkText("Sign up")).click()
    await driver.findElement(By.css(".mb-3:nth-child(1) > .form-control")).sendKeys("admin@venus.com")
    await driver.findElement(By.css(".mb-3:nth-child(2) > .form-control")).sendKeys("pass")
    await driver.findElement(By.css(".mb-3:nth-child(1) > .form-control")).click()
    await driver.findElement(By.css(".row:nth-child(2) > .row")).click()
    {
      const element = await driver.findElement(By.css(".row:nth-child(2) > .row"))
      await driver.actions({ bridge: true}).doubleClick(element).perform()
    }
    await driver.findElement(By.css(".mb-3:nth-child(1) > .form-control")).sendKeys("test@venus.com")
    await driver.findElement(By.css(".row:nth-child(2) > .row")).click()
    await driver.findElement(By.css(".mb-3:nth-child(3) > .form-control")).click()
    await driver.findElement(By.css(".mb-3:nth-child(3) > .form-control")).sendKeys("pass")
    await driver.findElement(By.css(".btn")).click()
    await driver.switchTo().frame(1)
    await driver.findElement(By.css("body")).click()
    await driver.close()
  })

  it('Validate User', async function() {
    await driver.get("http://localhost:3000/")
    await driver.manage().window().setRect({ width: 1720, height: 934 })
    await driver.findElement(By.linkText("Login/SignUp")).click()
    await driver.findElement(By.css(".mb-3:nth-child(1) > .form-control")).sendKeys("admin@venus.com")
    await driver.findElement(By.css(".mb-3:nth-child(2) > .form-control")).sendKeys("pass")
    await driver.findElement(By.css(".btn")).click()
    await driver.findElement(By.linkText("Admin")).click()
    await driver.findElement(By.css(".d-flex")).click()
    await driver.findElement(By.linkText("Logout")).click()
    await driver.findElement(By.css(".btn")).click()
    await driver.findElement(By.linkText("Login/SignUp")).click()
    await driver.findElement(By.css(".mb-3:nth-child(1) > .form-control")).sendKeys("admin@venus.com")
    await driver.findElement(By.css(".mb-3:nth-child(2) > .form-control")).sendKeys("pass")
    await driver.findElement(By.css(".row:nth-child(2) > .row")).click()
    await driver.findElement(By.css(".mb-3:nth-child(1) > .form-control")).sendKeys("test@venus.com")
    await driver.findElement(By.css(".mb-3:nth-child(2) > .form-control")).click()
    await driver.findElement(By.css(".mb-3:nth-child(2) > .form-control")).click()
    await driver.findElement(By.linkText("Sign up")).click()
    {
      const element = await driver.findElement(By.linkText("Sign up"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    await driver.findElement(By.css(".mb-3:nth-child(1) > .form-control")).sendKeys("admin@venus.com")
    await driver.findElement(By.css(".mb-3:nth-child(2) > .form-control")).sendKeys("pass")
    await driver.findElement(By.css(".mb-3:nth-child(1)")).click()
    await driver.findElement(By.linkText("Login/SignUp")).click()
    await driver.findElement(By.css(".mb-3:nth-child(1) > .form-control")).sendKeys("admin@venus.com")
    await driver.findElement(By.css(".mb-3:nth-child(2) > .form-control")).sendKeys("pass")
    await driver.findElement(By.css(".row:nth-child(2) > .row")).click()
    await driver.findElement(By.css(".mb-3:nth-child(1) > .form-control")).sendKeys("test@venus.com")
    await driver.findElement(By.css(".mb-3:nth-child(2) > .form-control")).click()
    await driver.findElement(By.css(".col:nth-child(3) .list-group-item:nth-child(1)")).click()
    await driver.findElement(By.css(".btn")).click()
    await driver.switchTo().frame(1)
    await driver.findElement(By.css("body")).click()
    await driver.close()
  })
})
